# Generated by Django 6.0.6 on 2026-07-06 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='is_public',
        ),
        migrations.AddField(
            model_name='entry',
            name='guest_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='guest name'),
        ),
        migrations.AddField(
            model_name='entry',
            name='visibility',
            field=models.CharField(choices=[('public', 'Synligt för alla'), ('members', 'Bara för inloggade')], default='public', max_length=20, verbose_name='visibility'),
        ),
    ]
