# Generated by Django 6.0.6 on 2026-07-06 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0002_remove_entry_is_public_entry_guest_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='visibility',
            field=models.CharField(choices=[('public', 'Alla'), ('members', 'Inloggade')], default='public', max_length=20, verbose_name='visibility'),
        ),
    ]
