# Generated by Django 6.0.6 on 2026-07-06 14:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0003_alter_entry_visibility'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['-start_date', '-created_at'], 'verbose_name': 'entry', 'verbose_name_plural': 'entries'},
        ),
        migrations.RemoveField(
            model_name='entry',
            name='visit_date',
        ),
        migrations.AddField(
            model_name='entry',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='end date'),
        ),
        migrations.AddField(
            model_name='entry',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='start date'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='visibility',
            field=models.CharField(choices=[('public', 'Alla'), ('members', 'Bara inloggade')], default='public', max_length=20, verbose_name='visibility'),
        ),
    ]
