# Generated by Django 6.0.6 on 2026-07-08 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0004_alter_entry_options_remove_entry_visit_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='guestbook.event', verbose_name='event'),
        ),
    ]
