# Generated by Django 6.0.6 on 2026-07-08 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0005_entry_event'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entryimage',
            options={'ordering': ['position', 'id'], 'verbose_name': 'entry image', 'verbose_name_plural': 'entry images'},
        ),
        migrations.AddField(
            model_name='entryimage',
            name='position',
            field=models.PositiveIntegerField(default=0, verbose_name='position'),
        ),
    ]
